apiVersion: v1
kind: PersistentVolume
metadata:
  name: hexa-database-volume
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/seb/Entwicklung/THI/Repositories/thi-snippets/cnd/ws-2024/26-spring-hexa-4/database"
