apiVersion: v1
kind: ConfigMap
metadata:
  name: hexa-database-config
data:
  MYSQL_USER: '{{ .Values.database.user }}'
  MYSQL_DATABASE: '{{ .Values.database.name }}'
---
apiVersion: v1
kind: Secret
metadata:
  name: hexa-database-secrets
stringData:
  MYSQL_ROOT_PASSWORD: '{{ .Values.database.rootPassword }}'
  MYSQL_PASSWORD: '{{ .Values.database.password }}'
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hexa-database-pv-claim
spec:
  storageClassName: {{ .Values.database.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: hexa-database
spec:
  ports:
    - port: 3306
  selector:
    app: database
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexa-database
spec:
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - image: mysql:5.7
          name: mysql
          envFrom:
            - configMapRef:
                name: hexa-database-config
            - secretRef:
                name: hexa-database-secrets
          ports:
            - containerPort: 3306
              name: database
          volumeMounts:
            - name: hexa-database-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: hexa-database-storage
          persistentVolumeClaim:
            claimName: hexa-database-pv-claim